### ISSUE TITLE
Automate SRTM download and preprocessing?

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/budyko-qgis#1]
The steps are:

1. Download relevant SRTM tiles from http://srtm.csi.cgiar.org/
1. Merge SRTM tiles in QGIS using Raster – Miscellaneous – Merge. Specify no data value as -32768! Sometimes the algorithm crashes on the way for reasons that are not understood, but still produces the merged layer. In this case you can proceed and manually add the new layer to the project.
1. Reproject to metric coordinate system (UTM) in QGIS using Raster-Projections-Warp. Specify no data value as -32768!
1. Aggregate SRTM to a suitable spatial resolution, using GRAS command r.resamp.stats from the Processing Toolbox in QGIS
1. Cut out region of interest in QGIS with Raster – Extraction – Clipper. Specify no data value as -32768!

OBS: Before running TauDEM algorithms, ensure that your no data value is a float (e.g. -32768) and not “nan” or similar. TauDEM does read the GDAL no-data tag (or similar) in the tiff metadata, but is unable to deal with non-float values in general. This can yield ridiculous results (particularly if you have ocean cells in your DEM).

**Comment by j08lue** [comment]
As for the SRTM download, there is a [SRTM download plugin for QGIS](https://plugins.qgis.org/plugins/SRTM-Downloader/), but it seems not to be easily scriptable. We could install it with the toolbox though and advise the users to use it. Only downside: This plugin requires a NASA Earthdata account, while SRTM can also be retrieved from anonymous sources.

Alternatives: we could use this code https://svn.openstreetmap.org/applications/utils/import/srtm2wayinfo/python/srtm.py and build our own downloader. Or we build on [our own Earthdata downloader](https://github.com/DHI-GRAS/earthdata-download).

But the most important part is actually the preprocessing with GDAL and GRASS.

**Comment by radosuav** [comment]
Steps 2-5 are implemented in [merge_and_warp](https://github.com/DHI-GRAS/budyko-qgis/blob/master/merge_and_warp.py) script.
