### ISSUE TITLE
Error in calibration due to Spotpy

### ISSUE THREAD

**Issue by KittelC** [DHI-GRAS/budyko-qgis#4]
Due to https://github.com/thouska/spotpy/pull/200 the calibration is searching for the worst model performance instead of the best due to a sign issue of the likelihood function. I have submitted a pull request - the code works with Spotpy 1.13.10 otherwise (but it would of course be better to use the newest version...). 

I also looked into getting the algorithm to use spotpy_multiobjective.py's objective function (it actually uses the default rmse, which amounts to the same, except it produces a positive number), but because the "negative likelihood" is hardcoded and not consistent, it seems hard to make a robust workaround. A part from this issue, the calibration implementation in QGIS runs smoothly with the test data, except a few tweaks to the calibration default settings (which I will also update in the code).

**Comment by j08lue** [comment]
Thanks for testing and the detailed explanation. We will be sure to include Spotpy 1.3.10 when we bundle it for this package and keep an eye on your PR going through. Let's keep this issue open until then.

**Comment by j08lue** [comment]
The PR in spotpy has been merged and we are now including version 1.4.6, which has the fix. Should be all good then, thanks again @KittelC.
